import type { GenerationTask } from "./types";

const now = new Date("2026-06-24T10:00:00.000Z").getTime();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "gen-1001",
    type: "image",
    model: "Midjourney v6",
    prompt: "Футуристичная станция метро в теплых оранжевых тонах, кинематографичный свет",
    status: "running",
    progress: 44,
    createdAt: minutesAgo(18),
    updatedAt: minutesAgo(1),
    startedAt: minutesAgo(12),
    etaSeconds: 42,
    credits: 24,
  },
  {
    id: "gen-1002",
    type: "text",
    model: "GPT-4o",
    prompt: "Собрать краткий план статьи о клиентской очереди генераций в SaaS-продукте",
    status: "running",
    progress: 72,
    createdAt: minutesAgo(15),
    updatedAt: minutesAgo(1),
    startedAt: minutesAgo(9),
    etaSeconds: 18,
    credits: 4,
  },
  {
    id: "gen-1003",
    type: "video",
    model: "Runway Gen-3",
    prompt: "Плавный пролет камеры над ночным городом, неон и мокрый асфальт",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
    etaSeconds: 180,
    credits: 68,
  },
  {
    id: "gen-1004",
    type: "audio",
    model: "Suno v4",
    prompt: "Короткий эмбиент-джингл для экрана ожидания генерации",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(10),
    updatedAt: minutesAgo(10),
    etaSeconds: 126,
    credits: 18,
  },
  {
    id: "gen-1005",
    type: "image",
    model: "FLUX Pro",
    prompt: "Минималистичный постер для презентации AI-инструментов ERA2",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
    etaSeconds: 58,
    credits: 16,
  },
  {
    id: "gen-1006",
    type: "text",
    model: "Claude 3.5 Sonnet",
    prompt: "Переписать описание продукта более спокойным и деловым тоном",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(44),
    updatedAt: minutesAgo(35),
    startedAt: minutesAgo(42),
    completedAt: minutesAgo(35),
    durationSeconds: 31,
    credits: 5,
    resultLabel: "Текст готов",
  },
  {
    id: "gen-1007",
    type: "image",
    model: "DALL-E 3",
    prompt: "Обложка для подборки нейросетей: темный фон, теплый акцент, чистая композиция",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(68),
    updatedAt: minutesAgo(59),
    startedAt: minutesAgo(66),
    completedAt: minutesAgo(59),
    durationSeconds: 84,
    credits: 22,
    resultLabel: "4 изображения",
  },
  {
    id: "gen-1008",
    type: "video",
    model: "Pika 2.0",
    prompt: "Переход от UI-макета к живому интерфейсу, крупный план прогресс-бара",
    status: "failed",
    progress: 37,
    createdAt: minutesAgo(92),
    updatedAt: minutesAgo(83),
    startedAt: minutesAgo(90),
    completedAt: minutesAgo(83),
    credits: 0,
    error: "Превышено время ожидания",
  },
  {
    id: "gen-1009",
    type: "audio",
    model: "Eleven Labs",
    prompt: "Озвучка короткого статуса: генерации идут, можно свернуть окно",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(120),
    etaSeconds: 74,
    credits: 7,
  },
  {
    id: "gen-1010",
    type: "text",
    model: "Gemini 2.0",
    prompt: "Сгенерировать варианты названий для новой коллекции шаблонов",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(4),
    updatedAt: minutesAgo(4),
    etaSeconds: 35,
    credits: 3,
  },
  {
    id: "gen-1011",
    type: "image",
    model: "Stable Diffusion 3",
    prompt: "Иконки для панели статуса генераций в едином стиле",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(3),
    updatedAt: minutesAgo(3),
    etaSeconds: 52,
    credits: 14,
  },
  {
    id: "gen-1012",
    type: "video",
    model: "Luma Dream Machine",
    prompt: "Короткий превью-ролик для карточки промо-кампании",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(2),
    updatedAt: minutesAgo(2),
    etaSeconds: 144,
    credits: 45,
  },
  {
    id: "gen-1013",
    type: "text",
    model: "GPT-4.1",
    prompt: "Подготовить варианты заголовков для страницы очереди",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(1),
    updatedAt: minutesAgo(1),
    etaSeconds: 38,
    credits: 4,
  },
  {
    id: "gen-1014",
    type: "image",
    model: "Ideogram 2.0",
    prompt: "Сгенерировать обложку для релиза интерфейса очереди",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(0),
    updatedAt: minutesAgo(0),
    etaSeconds: 63,
    credits: 17,
  },
  {
    id: "gen-1015",
    type: "audio",
    model: "Eleven Labs",
    prompt: "Озвучить уведомление о завершении нескольких задач",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(25),
    updatedAt: minutesAgo(25),
    etaSeconds: 82,
    credits: 8,
  },
  {
    id: "gen-1016",
    type: "video",
    model: "Runway Gen-3",
    prompt: "Сделать короткую демонстрацию прогресса генерации",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(26),
    updatedAt: minutesAgo(26),
    etaSeconds: 171,
    credits: 64,
  },
  {
    id: "gen-1017",
    type: "text",
    model: "Claude 3.5 Haiku",
    prompt: "Составить короткие подписи для статусов очереди",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(27),
    updatedAt: minutesAgo(27),
    etaSeconds: 31,
    credits: 3,
  },
  {
    id: "gen-1018",
    type: "image",
    model: "Midjourney v6",
    prompt: "Подготовить иллюстрацию для карточки активной генерации",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(28),
    updatedAt: minutesAgo(28),
    etaSeconds: 70,
    credits: 24,
  },
  {
    id: "gen-1019",
    type: "audio",
    model: "Suno v4",
    prompt: "Создать короткий звуковой сигнал для успешной генерации",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(150),
    updatedAt: minutesAgo(141),
    startedAt: minutesAgo(148),
    completedAt: minutesAgo(141),
    durationSeconds: 44,
    credits: 11,
    resultLabel: "Звук готов",
  },
  {
    id: "gen-1020",
    type: "video",
    model: "Pika 2.0",
    prompt: "Собрать превью-анимацию для панели задач",
    status: "failed",
    progress: 41,
    createdAt: minutesAgo(166),
    updatedAt: minutesAgo(158),
    startedAt: minutesAgo(164),
    completedAt: minutesAgo(158),
    credits: 0,
    error: "Модель временно недоступна",
  },
  {
    id: "gen-1021",
    type: "text",
    model: "Gemini 2.0",
    prompt: "Сформировать варианты описания результата генерации",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(190),
    updatedAt: minutesAgo(184),
    startedAt: minutesAgo(188),
    completedAt: minutesAgo(184),
    durationSeconds: 27,
    credits: 3,
    resultLabel: "Описание готово",
  },
];
