import type { GenerationTask } from "./types";

const now = new Date("2026-06-24T10:00:00.000Z").getTime();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "gen-1001",
    type: "image",
    model: "Midjourney v6",
    prompt: "Футуристичная станция метро в теплых оранжевых тонах, кинематографичный свет",
    status: "running",
    progress: 44,
    createdAt: minutesAgo(18),
    updatedAt: minutesAgo(1),
    startedAt: minutesAgo(12),
    etaSeconds: 42,
    credits: 24,
  },
  {
    id: "gen-1002",
    type: "text",
    model: "GPT-4o",
    prompt: "Собрать краткий план статьи о клиентской очереди генераций в SaaS-продукте",
    status: "running",
    progress: 72,
    createdAt: minutesAgo(15),
    updatedAt: minutesAgo(1),
    startedAt: minutesAgo(9),
    etaSeconds: 18,
    credits: 4,
  },
  {
    id: "gen-1003",
    type: "video",
    model: "Runway Gen-3",
    prompt: "Плавный пролет камеры над ночным городом, неон и мокрый асфальт",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
    etaSeconds: 180,
    credits: 68,
  },
  {
    id: "gen-1004",
    type: "audio",
    model: "Suno v4",
    prompt: "Короткий эмбиент-джингл для экрана ожидания генерации",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(10),
    updatedAt: minutesAgo(10),
    etaSeconds: 126,
    credits: 18,
  },
  {
    id: "gen-1005",
    type: "image",
    model: "FLUX Pro",
    prompt: "Минималистичный постер для презентации AI-инструментов ERA2",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
    etaSeconds: 58,
    credits: 16,
  },
  {
    id: "gen-1006",
    type: "text",
    model: "Claude 3.5 Sonnet",
    prompt: "Переписать описание продукта более спокойным и деловым тоном",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(44),
    updatedAt: minutesAgo(35),
    startedAt: minutesAgo(42),
    completedAt: minutesAgo(35),
    durationSeconds: 31,
    credits: 5,
    resultLabel: "Текст готов",
  },
  {
    id: "gen-1007",
    type: "image",
    model: "DALL-E 3",
    prompt: "Обложка для подборки нейросетей: темный фон, теплый акцент, чистая композиция",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(68),
    updatedAt: minutesAgo(59),
    startedAt: minutesAgo(66),
    completedAt: minutesAgo(59),
    durationSeconds: 84,
    credits: 22,
    resultLabel: "4 изображения",
  },
  {
    id: "gen-1008",
    type: "video",
    model: "Pika 2.0",
    prompt: "Переход от UI-макета к живому интерфейсу, крупный план прогресс-бара",
    status: "failed",
    progress: 37,
    createdAt: minutesAgo(92),
    updatedAt: minutesAgo(83),
    startedAt: minutesAgo(90),
    completedAt: minutesAgo(83),
    credits: 0,
    error: "Превышено время ожидания",
  },
  {
    id: "gen-1009",
    type: "audio",
    model: "ElevenLabs",
    prompt: "Озвучка короткого статуса: генерации идут, можно свернуть окно",
    status: "canceled",
    progress: 28,
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(112),
    startedAt: minutesAgo(118),
    completedAt: minutesAgo(112),
    credits: 7,
  },
  {
    id: "gen-1010",
    type: "text",
    model: "Gemini 2.0",
    prompt: "Сгенерировать варианты названий для новой коллекции шаблонов",
    status: "queued",
    progress: 0,
    createdAt: minutesAgo(4),
    updatedAt: minutesAgo(4),
    etaSeconds: 35,
    credits: 3,
  },
];
